// Generated by gencpp from file mira_communication/MiraAngles.msg
// DO NOT EDIT!


#ifndef MIRA_COMMUNICATION_MESSAGE_MIRAANGLES_H
#define MIRA_COMMUNICATION_MESSAGE_MIRAANGLES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mira_communication
{
template <class ContainerAllocator>
struct MiraAngles_
{
  typedef MiraAngles_<ContainerAllocator> Type;

  MiraAngles_()
    : joint_1(0.0)
    , joint_2(0.0)
    , joint_3(0.0)  {
    }
  MiraAngles_(const ContainerAllocator& _alloc)
    : joint_1(0.0)
    , joint_2(0.0)
    , joint_3(0.0)  {
  (void)_alloc;
    }



   typedef float _joint_1_type;
  _joint_1_type joint_1;

   typedef float _joint_2_type;
  _joint_2_type joint_2;

   typedef float _joint_3_type;
  _joint_3_type joint_3;





  typedef boost::shared_ptr< ::mira_communication::MiraAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mira_communication::MiraAngles_<ContainerAllocator> const> ConstPtr;

}; // struct MiraAngles_

typedef ::mira_communication::MiraAngles_<std::allocator<void> > MiraAngles;

typedef boost::shared_ptr< ::mira_communication::MiraAngles > MiraAnglesPtr;
typedef boost::shared_ptr< ::mira_communication::MiraAngles const> MiraAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mira_communication::MiraAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mira_communication::MiraAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mira_communication::MiraAngles_<ContainerAllocator1> & lhs, const ::mira_communication::MiraAngles_<ContainerAllocator2> & rhs)
{
  return lhs.joint_1 == rhs.joint_1 &&
    lhs.joint_2 == rhs.joint_2 &&
    lhs.joint_3 == rhs.joint_3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mira_communication::MiraAngles_<ContainerAllocator1> & lhs, const ::mira_communication::MiraAngles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mira_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mira_communication::MiraAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mira_communication::MiraAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mira_communication::MiraAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mira_communication::MiraAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mira_communication::MiraAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mira_communication::MiraAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mira_communication::MiraAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fb7487773865b96db936ca595817338";
  }

  static const char* value(const ::mira_communication::MiraAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fb7487773865b96ULL;
  static const uint64_t static_value2 = 0xdb936ca595817338ULL;
};

template<class ContainerAllocator>
struct DataType< ::mira_communication::MiraAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mira_communication/MiraAngles";
  }

  static const char* value(const ::mira_communication::MiraAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mira_communication::MiraAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 joint_1\n"
"float32 joint_2\n"
"float32 joint_3\n"
;
  }

  static const char* value(const ::mira_communication::MiraAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mira_communication::MiraAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_1);
      stream.next(m.joint_2);
      stream.next(m.joint_3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MiraAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mira_communication::MiraAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mira_communication::MiraAngles_<ContainerAllocator>& v)
  {
    s << indent << "joint_1: ";
    Printer<float>::stream(s, indent + "  ", v.joint_1);
    s << indent << "joint_2: ";
    Printer<float>::stream(s, indent + "  ", v.joint_2);
    s << indent << "joint_3: ";
    Printer<float>::stream(s, indent + "  ", v.joint_3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIRA_COMMUNICATION_MESSAGE_MIRAANGLES_H
