// Generated by gencpp from file mira_communication/PumpStatus.msg
// DO NOT EDIT!


#ifndef MIRA_COMMUNICATION_MESSAGE_PUMPSTATUS_H
#define MIRA_COMMUNICATION_MESSAGE_PUMPSTATUS_H

#include <ros/service_traits.h>


#include <mira_communication/PumpStatusRequest.h>
#include <mira_communication/PumpStatusResponse.h>


namespace mira_communication
{

struct PumpStatus
{

typedef PumpStatusRequest Request;
typedef PumpStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PumpStatus
} // namespace mira_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mira_communication::PumpStatus > {
  static const char* value()
  {
    return "c57caedf4aafd0b59704d2f3b16e0f35";
  }

  static const char* value(const ::mira_communication::PumpStatus&) { return value(); }
};

template<>
struct DataType< ::mira_communication::PumpStatus > {
  static const char* value()
  {
    return "mira_communication/PumpStatus";
  }

  static const char* value(const ::mira_communication::PumpStatus&) { return value(); }
};


// service_traits::MD5Sum< ::mira_communication::PumpStatusRequest> should match
// service_traits::MD5Sum< ::mira_communication::PumpStatus >
template<>
struct MD5Sum< ::mira_communication::PumpStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mira_communication::PumpStatus >::value();
  }
  static const char* value(const ::mira_communication::PumpStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mira_communication::PumpStatusRequest> should match
// service_traits::DataType< ::mira_communication::PumpStatus >
template<>
struct DataType< ::mira_communication::PumpStatusRequest>
{
  static const char* value()
  {
    return DataType< ::mira_communication::PumpStatus >::value();
  }
  static const char* value(const ::mira_communication::PumpStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mira_communication::PumpStatusResponse> should match
// service_traits::MD5Sum< ::mira_communication::PumpStatus >
template<>
struct MD5Sum< ::mira_communication::PumpStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mira_communication::PumpStatus >::value();
  }
  static const char* value(const ::mira_communication::PumpStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mira_communication::PumpStatusResponse> should match
// service_traits::DataType< ::mira_communication::PumpStatus >
template<>
struct DataType< ::mira_communication::PumpStatusResponse>
{
  static const char* value()
  {
    return DataType< ::mira_communication::PumpStatus >::value();
  }
  static const char* value(const ::mira_communication::PumpStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRA_COMMUNICATION_MESSAGE_PUMPSTATUS_H
