// Generated by gencpp from file mira_communication/SetAngles.msg
// DO NOT EDIT!


#ifndef MIRA_COMMUNICATION_MESSAGE_SETANGLES_H
#define MIRA_COMMUNICATION_MESSAGE_SETANGLES_H

#include <ros/service_traits.h>


#include <mira_communication/SetAnglesRequest.h>
#include <mira_communication/SetAnglesResponse.h>


namespace mira_communication
{

struct SetAngles
{

typedef SetAnglesRequest Request;
typedef SetAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAngles
} // namespace mira_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mira_communication::SetAngles > {
  static const char* value()
  {
    return "3ee1ad65a48008a184aaa3297a091e0f";
  }

  static const char* value(const ::mira_communication::SetAngles&) { return value(); }
};

template<>
struct DataType< ::mira_communication::SetAngles > {
  static const char* value()
  {
    return "mira_communication/SetAngles";
  }

  static const char* value(const ::mira_communication::SetAngles&) { return value(); }
};


// service_traits::MD5Sum< ::mira_communication::SetAnglesRequest> should match
// service_traits::MD5Sum< ::mira_communication::SetAngles >
template<>
struct MD5Sum< ::mira_communication::SetAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mira_communication::SetAngles >::value();
  }
  static const char* value(const ::mira_communication::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mira_communication::SetAnglesRequest> should match
// service_traits::DataType< ::mira_communication::SetAngles >
template<>
struct DataType< ::mira_communication::SetAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::mira_communication::SetAngles >::value();
  }
  static const char* value(const ::mira_communication::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mira_communication::SetAnglesResponse> should match
// service_traits::MD5Sum< ::mira_communication::SetAngles >
template<>
struct MD5Sum< ::mira_communication::SetAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mira_communication::SetAngles >::value();
  }
  static const char* value(const ::mira_communication::SetAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mira_communication::SetAnglesResponse> should match
// service_traits::DataType< ::mira_communication::SetAngles >
template<>
struct DataType< ::mira_communication::SetAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::mira_communication::SetAngles >::value();
  }
  static const char* value(const ::mira_communication::SetAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRA_COMMUNICATION_MESSAGE_SETANGLES_H
