// Generated by gencpp from file mira_communication/SetCoords.msg
// DO NOT EDIT!


#ifndef MIRA_COMMUNICATION_MESSAGE_SETCOORDS_H
#define MIRA_COMMUNICATION_MESSAGE_SETCOORDS_H

#include <ros/service_traits.h>


#include <mira_communication/SetCoordsRequest.h>
#include <mira_communication/SetCoordsResponse.h>


namespace mira_communication
{

struct SetCoords
{

typedef SetCoordsRequest Request;
typedef SetCoordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCoords
} // namespace mira_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mira_communication::SetCoords > {
  static const char* value()
  {
    return "346f5b8e72dfacf2ccf00e703a84e412";
  }

  static const char* value(const ::mira_communication::SetCoords&) { return value(); }
};

template<>
struct DataType< ::mira_communication::SetCoords > {
  static const char* value()
  {
    return "mira_communication/SetCoords";
  }

  static const char* value(const ::mira_communication::SetCoords&) { return value(); }
};


// service_traits::MD5Sum< ::mira_communication::SetCoordsRequest> should match
// service_traits::MD5Sum< ::mira_communication::SetCoords >
template<>
struct MD5Sum< ::mira_communication::SetCoordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mira_communication::SetCoords >::value();
  }
  static const char* value(const ::mira_communication::SetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mira_communication::SetCoordsRequest> should match
// service_traits::DataType< ::mira_communication::SetCoords >
template<>
struct DataType< ::mira_communication::SetCoordsRequest>
{
  static const char* value()
  {
    return DataType< ::mira_communication::SetCoords >::value();
  }
  static const char* value(const ::mira_communication::SetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mira_communication::SetCoordsResponse> should match
// service_traits::MD5Sum< ::mira_communication::SetCoords >
template<>
struct MD5Sum< ::mira_communication::SetCoordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mira_communication::SetCoords >::value();
  }
  static const char* value(const ::mira_communication::SetCoordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mira_communication::SetCoordsResponse> should match
// service_traits::DataType< ::mira_communication::SetCoords >
template<>
struct DataType< ::mira_communication::SetCoordsResponse>
{
  static const char* value()
  {
    return DataType< ::mira_communication::SetCoords >::value();
  }
  static const char* value(const ::mira_communication::SetCoordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRA_COMMUNICATION_MESSAGE_SETCOORDS_H
